##CLOCK
set_property PACKAGE_PIN W5 [get_ports clock_C]							
    set_property IOSTANDARD LVCMOS33 [get_ports clock_C]
	   create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clock_C]

##BUTTONS	   
set_property PACKAGE_PIN U18 [get_ports start]						
    set_property IOSTANDARD LVCMOS33 [get_ports start]
set_property PACKAGE_PIN T18 [get_ports main_reset]						
	set_property IOSTANDARD LVCMOS33 [get_ports main_reset]

##LED
set_property PACKAGE_PIN U16 [get_ports {result[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {result[0]}]
set_property PACKAGE_PIN E19 [get_ports {result[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {result[1]}]
set_property PACKAGE_PIN U19 [get_ports {result[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {result[2]}]
set_property PACKAGE_PIN V19 [get_ports {result[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {result[3]}]
set_property PACKAGE_PIN W18 [get_ports {result[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {result[4]}]
set_property PACKAGE_PIN U15 [get_ports {result[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {result[5]}]
set_property PACKAGE_PIN U14 [get_ports {result[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {result[6]}]
set_property PACKAGE_PIN V14 [get_ports {result[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {result[7]}]

##UI	
set_property PACKAGE_PIN V17 [get_ports {input[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input[0]}]
set_property PACKAGE_PIN V16 [get_ports {input[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input[1]}]
set_property PACKAGE_PIN W16 [get_ports {input[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input[2]}]
set_property PACKAGE_PIN W17 [get_ports {input[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input[3]}]
set_property PACKAGE_PIN W15 [get_ports {input[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input[4]}]
set_property PACKAGE_PIN V15 [get_ports {input[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input[5]}]
set_property PACKAGE_PIN W14 [get_ports {input[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input[6]}]
set_property PACKAGE_PIN W13 [get_ports {input[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {input[7]}]

##COMMAND	
set_property PACKAGE_PIN W2 [get_ports {action[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {action[0]}]
set_property PACKAGE_PIN U1 [get_ports {action[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {action[1]}]
set_property PACKAGE_PIN T1 [get_ports {action[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {action[2]}]
set_property PACKAGE_PIN R2 [get_ports {action[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {action[3]}]

##ADDRESS
set_property PACKAGE_PIN V2 [get_ports {address[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[0]}]
set_property PACKAGE_PIN T3 [get_ports {address[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[1]}]
set_property PACKAGE_PIN T2 [get_ports {address[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[2]}]
set_property PACKAGE_PIN R3 [get_ports {address[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {address[3]}]